# Generated by Django 5.0.2 on 2024-02-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emai',
            new_name='email',
        ),
    ]
